[workspace]
members = [
  "src/backend-engine",
  "src/backend-framework",
  "src/backend-server",
  "src/client-engine",
  "src/client-test",
  "src/common-build",
  "src/love-letter-backend",
  "src/mastermind-backend",
]
